Task 1

a) Filter out invalid transactions where the price is zero or the quantity is negative.

b) For each remaining transaction, compute a new field total = price * quantity.

c) Group the valid transactions by region and compute the total revenue per region. Store the result in a dictionary.

d) Print the region with the highest total revenue and its value using an f-string.

In [1]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]
valid_transactions=[]
for t in transactions:
   if t["price"] != 0 and t["quantity"] >= 0:
           valid_transactions.append(t)
print (valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}]


In [3]:
for vt in valid_transactions:
    vt["total"] = vt["price"] * vt["quantity"]
print (valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]


In [4]:
revenue_sorted_by_region = {}
for vt in valid_transactions:
    region = vt["region"]
    if region not in revenue_sorted_by_region:
        revenue_sorted_by_region[region] = 0
    revenue_sorted_by_region[region] += vt["total"]

print(revenue_sorted_by_region)

{'EU': 3600, 'US': 1050, 'APAC': 750}


In [6]:
highest_revenue_region = max(revenue_sorted_by_region, key=revenue_sorted_by_region.get)
print(f"the region with highest revenue is {highest_revenue_region}, and the revenue is {revenue_sorted_by_region[highest_revenue_region]}")

the region with highest revenue is EU, and the revenue is 3600


Task 2
Write a function called summarise_sales that takes a list of daily sales values and returns a dictionary containing:

"total": the sum of all daily sales

"average": the mean daily sales value, rounded to two decimals

"best_day": the index (starting from 1) of the day with the highest sales

"worst_day": the index (starting from 1) of the day with the lowest sales

"above_average_count": the number of days where sales exceeded the average

Call the function with the list above and print the returned dictionary.

In [14]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]
def summarise_sales(sales):
    total = sum(sales)
    average = round( total/ len(sales),2)
    best_day = sales.index(max(sales)) + 1
    worst_day = sales.index(min(sales)) +1
    above_average_count= 0
    for s in sales:
        if s > average:
            above_average_count += 1
    results = {
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count":above_average_count
    }
    return results
    
print (summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


Task 3: Using `for` loops and `if` statements, perform the following:

a) Create a new list called `passing` that contains only the names of students with a grade of 50 or above. Print the list.

b) Loop through the students and print a status message for each. If the student's grade is 80 or above, print `"[name]: Excellent"`; if between 50 and 79, print `"[name]: Pass"`; otherwise print `"[name]: Fail"`.

c) Count how many students have an attendance rate below 0.80. Print the count.

d) Find the student with the highest grade using a loop (do not use `max()`). Print the student's name and grade.

e) Now find the student with the highest grade using `max()`. Print the student's name and grade.

In [5]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]
passing = [] 
for s in students:
    if s["grade"] >= 50:
        passing.append(s["name"])
print(passing)

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']


In [11]:
for s in students:
    if s["grade"] >= 80:
        print(f"{s["name"]}:Excellent")
    elif s["grade"] >= 50:
        print(f"{s["name"]}:Pass")
    else:
        print(f"{s["name"]}:Fail")
     

Anna:Excellent
Erik:Pass
Mia:Excellent
Leo:Fail
Sara:Pass
Tom:Pass
Nina:Excellent
Olli:Pass


In [12]:
count_low_attendance_rate = 0
for s in students:
    if s["attendance"] < 0.8:
        count_low_attendance_rate += 1
print(count_low_attendance_rate)

4


In [21]:
# Find the student with the highest grade using a loop (do not use `max()`). Print the student's name and grade.
highest_grade = 0
for s in students:
    if s["grade"] > highest_grade:
        highest_grade = s["grade"]
        student_with_highest_grade = s
print(f"student with highest grade: {student_with_highest_grade["name"]}, grade: {highest_grade}")

    

student with highest grade: Nina, grade: 95


In [20]:
# Now find the student with the highest grade using `max()`. Print the student's name and grade.
best_student = max(students, key = lambda s : s["grade"])
print(f"student with highest grade: {best_student["name"]}, grade: {best_student["grade"]}")

student with highest grade: Nina, grade: 95


Task 4: Class and methods
a) A method add_asset(ticker, shares, price_per_share) that adds a new asset or updates the number of shares if the ticker already exists (in which case the price should also be updated).

b) A method total_value() that returns the total market value of the portfolio.

c) A method most_valuable() that returns the ticker of the asset with the highest total value (shares × price).

d) A __str__ method that returns a readable summary of the portfolio, including the owner's name, the number of assets, and the total value.

Create an instance, add at least three assets, and demonstrate all methods with printed output.

In [29]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share):
        self.holdings[ticker]= {
            "shares":shares,
            "price_per_share":price_per_share
        }
        
    def total_value(self):
        total = 0
        for ticker in self.holdings:
            total += self.holdings[ticker]["shares"]* self.holdings[ticker]["price_per_share"]
        return total
        
    def most_valuable(self):
        mv_ticker = None
        mv = 0
        for ticker in self.holdings:
            asset = self.holdings[ticker]
            value = asset["shares"]*asset["price_per_share"]
            if value > mv:
                mv = value
                mv_ticker = ticker
        return mv_ticker

    def __str__(self):
        return (f"owner's name: {self.owner}, number of assets: {len(self.holdings)}, total value: {self.total_value()}")

p = Portfolio("Chen")
p.add_asset("AAPL",100,260)
p.add_asset("MSFT",300,400)
p.add_asset("NVDA",200,180)
print (p)
print(p.most_valuable())

owner's name: Chen, number of assets: 3, total value: 182000
MSFT


 Task 5: Importing a module
 Using the datetime module, parse each date string into a datetime.date object. 
 Compute and print the number of days between the earliest and latest order.

In [35]:
from datetime import date

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]
dates = []

for order in orders:
    d = date.fromisoformat(order[0])
    dates.append(d)

print(dates)



[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3), datetime.date(2025, 2, 14), datetime.date(2025, 3, 1), datetime.date(2025, 3, 10), datetime.date(2025, 3, 22), datetime.date(2025, 4, 5)]


In [37]:
earliest = min(dates)
latest = max(dates)
diff = latest - earliest
print(f"the number of days between the earliest and latest order: {diff.days} days")  #.days——delete extra part: 80 days, 0:00:00——80

the number of days between the earliest and latest order: 80 days


Task 6: Array Operations and Broadcasting
a) Compute and print the total annual revenue for each year (i.e., row sums). Use the axis parameter.

b) Compute the mean quarterly revenue across all years (i.e., column means).

c) Using broadcasting, apply a growth adjustment to the 2024 row by multiplying it element-wise with the array [1.05, 1.03, 1.08, 1.02]. Print the adjusted values.

d) Use boolean indexing to find and print all quarterly revenue values that exceed 250 (thousands of euros).

In [39]:
# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
import numpy as np
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])
print(revenue)

[[210 230 190 250]
 [220 260 200 270]
 [250 290 230 310]]


In [41]:
annual = revenue.sum(axis=1)
print(annual)

[ 880  950 1080]


In [45]:
mean_quarterly_revenue = np.round(revenue.mean(axis=0),2)
print(mean_quarterly_revenue)

[226.67 260.   206.67 276.67]


In [46]:
growth_rate = np.array([1.05, 1.03, 1.08, 1.02])
adjusted_2024 = revenue[2] * growth_rate
print(adjusted_2024)

[262.5 298.7 248.4 316.2]


In [49]:
print(revenue[revenue > 250])

[260 270 290 310]


task7 Pandas 
a) Add a new column salary_per_year_exp computed as salary / years_exp. Round to the nearest integer.

b) Sort the DataFrame by performance_score in descending order and print the top 3 employees.

c) Using .loc, select all employees in the Finance department with a performance score above 4.0. Print the result.

d) Rename the column years_exp to experience_years using the .rename() method.

e) Using .iloc, select and print the salary and performance score columns for the first four employees.

In [50]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)
print(df)

  employee department  salary  years_exp  performance_score
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9


In [51]:
df["salary_per_year_exp"] = (df["salary"]/df["years_exp"]).round()
print(df)

  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
1     Erik  Marketing    4000          3                3.8   
2      Mia    Finance    4800          7                4.5   
3      Leo         IT    5200         10                4.0   
4     Sara  Marketing    3900          2                3.5   
5      Tom         IT    5100          8                4.9   

   salary_per_year_exp  
0                900.0  
1               1333.0  
2                686.0  
3                520.0  
4               1950.0  
5                638.0  


In [52]:
# b) Sort the DataFrame by performance_score in descending order and print the top 3 employees.
sorted = df.sort_values("performance_score", ascending=False)
print(sorted.head(3))


  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  


In [54]:
# c) Using .loc, select all employees in the Finance department with a performance score above 4.0. Print the result.
employees_finance = df.loc[(df["department"] == "Finance") & (df["performance_score"] > 4.0)]
print(employees_finance)

  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  


In [56]:
# d) Rename the column years_exp to experience_years using the .rename() method.
df = df.rename(columns={"years_exp":"experience_years"}) #{key:value}
print(df)


  employee department  salary  experience_years  performance_score  \
0     Anna    Finance    4500                 5                4.2   
1     Erik  Marketing    4000                 3                3.8   
2      Mia    Finance    4800                 7                4.5   
3      Leo         IT    5200                10                4.0   
4     Sara  Marketing    3900                 2                3.5   
5      Tom         IT    5100                 8                4.9   

   salary_per_year_exp  
0                900.0  
1               1333.0  
2                686.0  
3                520.0  
4               1950.0  
5                638.0  


In [60]:
# e) Using .iloc, select and print the salary and performance score columns for the first four employees. 
print(df.iloc[:4,[2,4]])

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


Task 8: More Pandas 
a) Create a DataFrame with columns: date, visitors, conversion_rate, and avg_order_value. Set date as the index.

b) Compute two new columns: conversions (= visitors × conversion_rate, rounded to the nearest integer) and daily_revenue (= conversions × avg_order_value).

In [63]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123) # seem result every time
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

df = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})
df = df.set_index("date")
print(df)

            visitors  conversion_rate  avg_order_value
date                                                  
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39
2025-01-11       288           0.0511            46.07
2025-01-12       302           0.0339            72.90
2025-01-13       273           0.0300            42.82
2025-01-14       333           0.0499            50.33
2025-01-15       270           0.0550            50.28
2025-01-16       339           0.0311            50.28
2025-01-17       524           0.0209            50.55
2025-01-18       380           0.0483            45.18
2025-01-19       569           0.0637            44.17
2025-01-20       379           0.0751            41.38
2025-01-21       310           0.0575            35.12
2025-01-22

#b) Compute two new columns: conversions (= visitors × conversion_rate, rounded to the nearest integer) and daily_revenue (= conversions × avg_order_value).

In [64]:
df["conversions"] = (df["visitors"] * df["conversion_rate"]).round()
df["daily_revenue"] = (df["conversions"] * df["avg_order_value"])
print(df)

            visitors  conversion_rate  avg_order_value  conversions  \
date                                                                  
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   
2025-01-11       288           0.0511            46.07         15.0   
2025-01-12       302           0.0339            72.90         10.0   
2025-01-13       273           0.0300            42.82          8.0   
2025-01-14       333           0.0499            50.33         17.0   
2025-01-15       270           0.0550            50.28         15.0   
2025-01-16       339           0.0311            50.28         11.0   
2025-01-17       524           0.0209            50.55         11.0   
2025-0